services:
  postgres:
    image: postgres:13
    container_name: magnify_postgres
    networks:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: magnify_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  postgres:
    external: true

volumes:
  postgres_data: